export default {
  SIGNIN: 'SIGNIN',
  SIGNUP: 'SIGNUP',
  LOGOUT: 'LOGOUT',
  GET_USER: 'GET_USER',
  SET_USERNAME: 'SET_USERNAME',
  SIGNGOOGLE: 'SIGNGOOGLE',
  SIGNFACEBOOK: 'SIGNFACEBOOK',
  CREATE_USER: 'CREATE_USER',
  WRITE_MESSAGE: 'WRITE_MESSAGE'
};
