export default {
  SEND_MESSAGE: 'server/SEND_MESSAGE',
  RECEIVE_MESSAGES: 'RECEIVE_MESSAGES',
  SIGNIN: 'SIGNIN',
  SIGNUP: 'SIGNUP',
  LOGOUT: 'LOGOUT',
  GET_USER: 'GET_USER',
  SET_USERNAME: 'SET_USERNAME',
  SIGNGOOGLE: 'SIGNGOOGLE',
  SIGNFACEBOOK: 'SIGNFACEBOOK'
};
